# sa
apiVersion: v1
kind: ServiceAccount
metadata:
  name: polaris
  namespace: default
  labels:
    app: polaris
---
# sa
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubexp
  namespace: default
  labels:
    app: kubexp
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: polaris
  labels:
    app: polaris
rules:
  - apiGroups:
      - ''
    resources:
      - 'nodes'
    verbs:
      - 'get'
      - 'list'
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: polaris-view
  labels:
    app: polaris
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
  - kind: ServiceAccount
    name: polaris
    namespace: polaris
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: polaris
  labels:
    app: polaris
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: polaris
subjects:
  - kind: ServiceAccount
    name: polaris
    namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: kubexp
  labels:
    app: kubexp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: kubexp
    namespace: default
# server
apiVersion: v1
kind: Service
metadata:
  labels:
    app: xos
  name: xos
spec:
  ports:
  - name: polaris
    port: 2666
    protocol: TCP
    targetPort: 2666
    nodePort: 36666
  - name: kubexp
    port: 2555
    protocol: TCP
    targetPort: 2555
    nodePort: 35555
  - name: goserver
    port: 2444
    protocol: TCP
    targetPort: 2444
    nodePort: 34444
  - name: gofs
    port: 2333
    protocol: TCP
    targetPort: 2333
    nodePort: 33333
  - name: webssh
    port: 2222
    protocol: TCP
    targetPort: 2222
    nodePort: 32222
  selector:
    app: xos
  sessionAffinity: None
  type: NodePort

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: xossh
  namespace: ingress-nginx
data:
  "2233": xshrim/xossh:2233

---
apiVersion: v1
kind: Service
metadata:
  name: xossh
  namespace: xshrim
spec:
  selector:
    app: xos
  ports:
    - port: 2233
      targetPort: 22
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xos
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: xos
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: xos
    spec:
      containers:
      - name: xos
        image: xo
        imagePullPolicy: Always
        #command:
        #- gofs
        #command:
        #- /root/webssh
        #command:
        #- bash
        #- /root/run.sh
        #livenessProbe:
          #failureThreshold: 3
          #initialDelaySeconds: 10
          #periodSeconds: 2
          #successThreshold: 1
          #tcpSocket:
            #port: 2333
          #timeoutSeconds: 2
        #readinessProbe:
          #failureThreshold: 3
          #initialDelaySeconds: 10
          #periodSeconds: 2
          #successThreshold: 2
          #tcpSocket:
            #port: 2333
          #timeoutSeconds: 2
        env:
        - name: WEBHOST
          value: share.demo.com
        - name: WEBPORT
          value: "80"
        - name: HSUSER               # access user for gohttpserver
          value: admin
        - name: HSPASSWD             # access password for gohttpserver
          value: Transfer@123
        - name: HSDIR                # directory for gohttpserver
          value: /share
        - name: HOST                 # default remote host which webssh connects to    
          value: "127.0.0.1"
        - name: PORT                 # default remote port which webssh connects to
          value: "22"
        - name: USER                 # default remote user which webssh connects with
          value: root
        - name: PASSWD               # default remote password which webssh connects with
          value: admin
        - name: TIMEOUT              # webssh timeout  
          value: "600"
        - name: SSL                  # enable ssl for webssh
          value: "true"
        - name: HSPORT          # default port for polaris server
          value: "2444"
        - name: SSH         # run ssh daemon
          value: "true"
        - name: SAMBA       # not run samba daemon
          value: "false"
        - name: GOFS        # run gofs file server
          value: "true"
        - name: HS          # not run gohttpserver
          value: "false"
        - name: WEBSSH      # run webssh server
          value: "true"
        - name: POLARIS     # run polaris
          value: "false"
        - name: KUBEXP      # run kubexp
          value: "true"
        ports:
        - containerPort: 2666
          name: polaris
          protocol: TCP
        - containerPort: 2555
          name: kubexp
          protocol: TCP
        - containerPort: 2444
          name: goserver
          protocol: TCP
        - containerPort: 2333
          name: gofs
          protocol: TCP
        - containerPort: 2222
          name: webssh
          protocol: TCP
        - containerPort: 22
          name: ssh
          protocol: TCP
        resources: 
          limits:
            cpu: 500m
            memory: 256Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsConfig: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccountName: polaris
      securityContext: {}
      terminationGracePeriodSeconds: 30

# client
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: xoc
  name: xoc
spec:
  ports:
  - name: default
    port: 2334
    protocol: TCP
    targetPort: 2334
  selector:
    app: xoc
  sessionAffinity: None
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xoc
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: xoc
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: xoc
    spec:
      containers:
      - image: xo
        imagePullPolicy: Always
        args:
        - tail
        - -f
        - /dev/null
        name: xoc
        ports:
        - containerPort: 2334
          name: http
          protocol: TCP
        resources: 
          limits:
            cpu: 200m
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsConfig: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccountName: polaris
      securityContext: {}
      terminationGracePeriodSeconds: 30
